"""empty message

Revision ID: 298febe696eb
Revises: 
Create Date: 2018-04-25 02:49:40.570929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298febe696eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.String(length=16), nullable=True),
    sa.Column('p_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regionName', sa.String(length=16), nullable=True),
    sa.Column('cityCode', sa.Integer(), nullable=True),
    sa.Column('pinYin', sa.String(length=128), nullable=True),
    sa.Column('letter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['letter'], ['letter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('person')
    op.drop_table('letter')
    # ### end Alembic commands ###
